In [9]:
import numpy as np

a = np.arange(15).reshape(3, 5)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype.name)
print(a.itemsize)
print(a.size)
print(type(a))
b = np.array([6, 7, 8])
print(b)
print(type(b))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int64
8
15
<class 'numpy.ndarray'>
[6 7 8]
<class 'numpy.ndarray'>


In [11]:
a = np.array([2, 3, 4])
print(a)
print(a.dtype)
b = np.array([1.5, 3.2, 1.1])
print(b.dtype)

[2 3 4]
int64
float64


In [13]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [14]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [19]:
print(np.zeros((3, 4)))
print(np.ones((2, 3, 4), dtype=np.int16)) # dtype can also be specified
print(np.empty((2, 3))) # uninitialized

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]


In [21]:
print(np.arange(10, 30, 5))
print(np.arange(0, 2, 0.3)) # it accepts float arguments

[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [23]:
from numpy import pi

print(np.linspace(0, 2, 9)) # 9 numbers from 0 to 2
x = np.linspace(0, 2*pi, 100) # useful to evaluate function at lots of points
f = np.sin(x)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [26]:
a = np.arange(6) # 1d array
print(a)
b = np.arange(12).reshape(4, 3) # 2d array
print(b)
c = np.arange(24).reshape(2, 3, 4) # 3d array
print(c)

[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [28]:
print(np.arange(10000))
print(np.arange(10000).reshape(100, 100))

# to avoid this - np.set_printoptions(threshold=sys.maxsize) # sys module shold be imported

[   0    1    2 ... 9997 9998 9999]
[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [34]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(b)
c = a - b
print(c)
print(b ** 2)
print(10 * np.sin(a))
print(a < 35)

[0 1 2 3]
[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]
